package io.openai.model

import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A chat completion message generated by the model.
 */
@Serializable
public data class ChatCompletionResponseMessage(
  public val content: String?,
  public val refusal: String?,
  @SerialName("tool_calls")
  public val toolCalls: ChatCompletionMessageToolCalls? = null,
  public val annotations: List<Annotations>? = null,
  public val role: Role,
  @SerialName("function_call")
  public val functionCall: FunctionCall? = null,
  public val audio: Audio? = null,
) {
  /**
   * A URL citation when using web search.
   *
   */
  @Serializable
  public data class Annotations(
    public val type: Type,
    @SerialName("url_citation")
    public val urlCitation: UrlCitation,
  ) {
    @Serializable
    public enum class Type(
      public val `value`: String,
    ) {
      @SerialName("url_citation")
      UrlCitation("url_citation"),
      ;
    }

    /**
     * A URL citation when using web search.
     */
    @Serializable
    public data class UrlCitation(
      @SerialName("end_index")
      public val endIndex: Long,
      @SerialName("start_index")
      public val startIndex: Long,
      public val url: String,
      public val title: String,
    )
  }

  /**
   * If the audio output modality is requested, this object contains data
   * about the audio response from the model. [Learn more](/docs/guides/audio).
   *
   */
  @Serializable
  public data class Audio(
    public val id: String,
    @SerialName("expires_at")
    public val expiresAt: Long,
    public val `data`: String,
    public val transcript: String,
  )

  /**
   * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
   */
  @Serializable
  public data class FunctionCall(
    public val arguments: String,
    public val name: String,
  )

  @Serializable
  public enum class Role(
    public val `value`: String,
  ) {
    @SerialName("assistant")
    Assistant("assistant"),
    ;
  }
}
