package io.openai.model

import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement

/**
 * Messages sent by the model in response to user messages.
 *
 */
@Serializable
public data class ChatCompletionRequestAssistantMessage(
  public val content: Content? = null,
  public val refusal: String? = null,
  public val role: Role,
  public val name: String? = null,
  public val audio: Audio? = null,
  @SerialName("tool_calls")
  public val toolCalls: ChatCompletionMessageToolCalls? = null,
  @SerialName("function_call")
  public val functionCall: FunctionCall? = null,
) {
  /**
   * Data about a previous audio response from the model.
   * [Learn more](/docs/guides/audio).
   *
   */
  @JvmInline
  @Serializable
  public value class Audio(
    public val id: String,
  )

  /**
   * The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
   *
   */
  @Serializable(with = Content.Serializer::class)
  public sealed interface Content {
    @Serializable
    @JvmInline
    public value class CaseString(
      public val `value`: String,
    ) : Content

    @Serializable
    @JvmInline
    public value class CaseChatCompletionRequestAssistantMessageContentPartList(
      public val `value`: List<ChatCompletionRequestAssistantMessageContentPart>,
    ) : Content

    public object Serializer : KSerializer<Content> {
      @OptIn(
        InternalSerializationApi::class,
        ExperimentalSerializationApi::class,
      )
      override val descriptor: SerialDescriptor =
          buildSerialDescriptor("io.openai.model.ChatCompletionRequestAssistantMessage.Content", PolymorphicKind.SEALED) {
        element("CaseString", String.serializer().descriptor)
        element("CaseChatCompletionRequestAssistantMessageContentPartList", ListSerializer(ChatCompletionRequestAssistantMessageContentPart.serializer()).descriptor)
      }

      override fun deserialize(decoder: Decoder): Content {
        val value = decoder.decodeSerializableValue(JsonElement.serializer())
        val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
        return json.attemptDeserialize(
          value,
          CaseChatCompletionRequestAssistantMessageContentPartList::class to { CaseChatCompletionRequestAssistantMessageContentPartList(decodeFromJsonElement(ListSerializer(ChatCompletionRequestAssistantMessageContentPart.serializer()), it)) },
          CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
        )
      }

      override fun serialize(encoder: Encoder, `value`: Content) {
        when(value) {
          is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
          is CaseChatCompletionRequestAssistantMessageContentPartList -> encoder.encodeSerializableValue(ListSerializer(ChatCompletionRequestAssistantMessageContentPart.serializer()), value.value)
        }
      }
    }
  }

  /**
   * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
   */
  @Serializable
  public data class FunctionCall(
    public val arguments: String,
    public val name: String,
  )

  @Serializable
  public enum class Role(
    public val `value`: String,
  ) {
    @SerialName("assistant")
    Assistant("assistant"),
    ;
  }
}
