package io.openai.model

import kotlin.OptIn
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * The tool calls generated by the model, such as function calls.
 */
@JvmInline
@Serializable
public value class ChatCompletionMessageToolCalls(
  public val items: List<Item>,
) {
  @OptIn(ExperimentalSerializationApi::class)
  @JsonClassDiscriminator("type")
  @Serializable
  public sealed interface Item {
    @Serializable
    @JvmInline
    @SerialName("ChatCompletionMessageToolCall")
    public value class ChatCompletionMessageToolCall(
      public val `value`: io.openai.model.ChatCompletionMessageToolCall,
    ) : Item

    @Serializable
    @JvmInline
    @SerialName("ChatCompletionMessageCustomToolCall")
    public value class ChatCompletionMessageCustomToolCall(
      public val `value`: io.openai.model.ChatCompletionMessageCustomToolCall,
    ) : Item
  }
}
