package io.openai.model

import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * The tool calls generated by the model, such as function calls.
 */
@JvmInline
@Serializable
public value class ChatCompletionMessageToolCalls(
  public val items: List<Item>,
) {
  @OptIn(ExperimentalSerializationApi::class)
  @JsonClassDiscriminator("type")
  @Serializable
  public sealed interface Item {
    /**
     * A call to a function tool created by the model.
     *
     */
    @SerialName("function")
    @Serializable
    public data class Function(
      public val id: String,
      public val function: Function,
    ) : Item {
      /**
       * The function that the model called.
       */
      @Serializable
      public data class Function(
        public val name: String,
        public val arguments: String,
      )
    }

    /**
     * A call to a custom tool created by the model.
     *
     */
    @SerialName("custom")
    @Serializable
    public data class Custom(
      public val id: String,
      public val custom: Custom,
    ) : Item {
      /**
       * The custom tool that the model called.
       */
      @Serializable
      public data class Custom(
        public val name: String,
        public val input: String,
      )
    }
  }
}
