package io.openai.model

import kotlin.Boolean
import kotlin.Long
import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement

/**
 * An object representing a list of chat completion messages.
 *
 */
@Serializable
public data class ChatCompletionMessageList(
  @Required
  public val `object`: Object = Object.List,
  public val `data`: List<Data>,
  @SerialName("first_id")
  public val firstId: String,
  @SerialName("last_id")
  public val lastId: String,
  @SerialName("has_more")
  public val hasMore: Boolean,
) {
  /**
   * A chat completion message generated by the model.
   */
  @Serializable
  public data class Data(
    public val content: String?,
    public val refusal: String?,
    @SerialName("tool_calls")
    public val toolCalls: ChatCompletionMessageToolCalls? = null,
    public val annotations: List<Annotations>? = null,
    public val role: Role,
    @SerialName("function_call")
    public val functionCall: FunctionCall? = null,
    public val audio: Audio? = null,
    public val id: String? = null,
    @SerialName("content_parts")
    public val contentParts: List<ContentParts>? = null,
  ) {
    /**
     * A URL citation when using web search.
     *
     */
    @Serializable
    public data class Annotations(
      public val type: Type,
      @SerialName("url_citation")
      public val urlCitation: UrlCitation,
    ) {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("url_citation")
        UrlCitation("url_citation"),
        ;
      }

      /**
       * A URL citation when using web search.
       */
      @Serializable
      public data class UrlCitation(
        @SerialName("end_index")
        public val endIndex: Long,
        @SerialName("start_index")
        public val startIndex: Long,
        public val url: String,
        public val title: String,
      )
    }

    /**
     * If the audio output modality is requested, this object contains data
     * about the audio response from the model. [Learn more](/docs/guides/audio).
     *
     */
    @Serializable
    public data class Audio(
      public val id: String,
      @SerialName("expires_at")
      public val expiresAt: Long,
      public val `data`: String,
      public val transcript: String,
    )

    @Serializable(with = ContentParts.Serializer::class)
    public sealed interface ContentParts {
      @Serializable
      @JvmInline
      public value class CaseChatCompletionRequestMessageContentPartText(
        public val `value`: ChatCompletionRequestMessageContentPartText,
      ) : ContentParts

      @Serializable
      @JvmInline
      public value class CaseChatCompletionRequestMessageContentPartImage(
        public val `value`: ChatCompletionRequestMessageContentPartImage,
      ) : ContentParts

      public object Serializer : KSerializer<ContentParts> {
        @OptIn(
          InternalSerializationApi::class,
          ExperimentalSerializationApi::class,
        )
        override val descriptor: SerialDescriptor =
            buildSerialDescriptor("io.openai.model.ChatCompletionMessageList.Data.ContentParts", PolymorphicKind.SEALED) {
          element("CaseChatCompletionRequestMessageContentPartText", ChatCompletionRequestMessageContentPartText.serializer().descriptor)
          element("CaseChatCompletionRequestMessageContentPartImage", ChatCompletionRequestMessageContentPartImage.serializer().descriptor)
        }

        override fun deserialize(decoder: Decoder): ContentParts {
          val value = decoder.decodeSerializableValue(JsonElement.serializer())
          val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
          return json.attemptDeserialize(
            value,
            CaseChatCompletionRequestMessageContentPartText::class to { CaseChatCompletionRequestMessageContentPartText(decodeFromJsonElement(ChatCompletionRequestMessageContentPartText.serializer(), it)) },
            CaseChatCompletionRequestMessageContentPartImage::class to { CaseChatCompletionRequestMessageContentPartImage(decodeFromJsonElement(ChatCompletionRequestMessageContentPartImage.serializer(), it)) },
          )
        }

        override fun serialize(encoder: Encoder, `value`: ContentParts) {
          when(value) {
            is CaseChatCompletionRequestMessageContentPartText -> encoder.encodeSerializableValue(ChatCompletionRequestMessageContentPartText.serializer(), value.value)
            is CaseChatCompletionRequestMessageContentPartImage -> encoder.encodeSerializableValue(ChatCompletionRequestMessageContentPartImage.serializer(), value.value)
          }
        }
      }
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     */
    @Serializable
    public data class FunctionCall(
      public val arguments: String,
      public val name: String,
    )

    @Serializable
    public enum class Role(
      public val `value`: String,
    ) {
      @SerialName("assistant")
      Assistant("assistant"),
      ;
    }
  }

  @Serializable
  public enum class Object(
    public val `value`: String,
  ) {
    @SerialName("list")
    List("list"),
    ;
  }
}
