package io.openai.model

import kotlin.Boolean
import kotlin.Long
import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * An object representing a list of chat completion messages.
 *
 */
@Serializable
public data class ChatCompletionMessageList(
  @Required
  public val `object`: Object = Object.List,
  public val `data`: List<Data>,
  @SerialName("first_id")
  public val firstId: String,
  @SerialName("last_id")
  public val lastId: String,
  @SerialName("has_more")
  public val hasMore: Boolean,
) {
  /**
   * A chat completion message generated by the model.
   */
  @Serializable
  public data class Data(
    public val content: String?,
    public val refusal: String?,
    @SerialName("tool_calls")
    public val toolCalls: ChatCompletionMessageToolCalls? = null,
    public val annotations: List<Annotations>? = null,
    public val role: Role,
    @SerialName("function_call")
    public val functionCall: FunctionCall? = null,
    public val audio: Audio? = null,
    public val id: String? = null,
    @SerialName("content_parts")
    public val contentParts: List<ContentParts>? = null,
  ) {
    /**
     * A URL citation when using web search.
     *
     */
    @Serializable
    public data class Annotations(
      public val type: Type,
      @SerialName("url_citation")
      public val urlCitation: UrlCitation,
    ) {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("url_citation")
        UrlCitation("url_citation"),
        ;
      }

      /**
       * A URL citation when using web search.
       */
      @Serializable
      public data class UrlCitation(
        @SerialName("end_index")
        public val endIndex: Long,
        @SerialName("start_index")
        public val startIndex: Long,
        public val url: String,
        public val title: String,
      )
    }

    /**
     * If the audio output modality is requested, this object contains data
     * about the audio response from the model. [Learn more](/docs/guides/audio).
     *
     */
    @Serializable
    public data class Audio(
      public val id: String,
      @SerialName("expires_at")
      public val expiresAt: Long,
      public val `data`: String,
      public val transcript: String,
    )

    @OptIn(ExperimentalSerializationApi::class)
    @JsonClassDiscriminator("type")
    @Serializable
    public sealed interface ContentParts {
      /**
       * Learn about [text inputs](/docs/guides/text-generation).
       *
       */
      @JvmInline
      @SerialName("text")
      @Serializable
      public value class Text(
        public val text: String,
      ) : ContentParts

      /**
       * Learn about [image inputs](/docs/guides/vision).
       *
       */
      @SerialName("image_url")
      @Serializable
      public data class ImageUrl(
        public val url: String,
        public val detail: Detail? = null,
      ) : ContentParts {
        @Serializable
        public enum class Detail(
          public val `value`: String,
        ) {
          @SerialName("auto")
          Auto("auto"),
          @SerialName("low")
          Low("low"),
          @SerialName("high")
          High("high"),
          ;
        }
      }
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     */
    @Serializable
    public data class FunctionCall(
      public val arguments: String,
      public val name: String,
    )

    @Serializable
    public enum class Role(
      public val `value`: String,
    ) {
      @SerialName("assistant")
      Assistant("assistant"),
      ;
    }
  }

  @Serializable
  public enum class Object(
    public val `value`: String,
  ) {
    @SerialName("list")
    List("list"),
    ;
  }
}
