package io.openai.model

import kotlin.String
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
 */
@Serializable
public data class CompactionBody(
  @Required
  public val type: Type = Type.Compaction,
  public val id: String,
  @SerialName("encrypted_content")
  public val encryptedContent: String,
  @SerialName("created_by")
  public val createdBy: String? = null,
) {
  @Serializable
  public enum class Type(
    public val `value`: String,
  ) {
    @SerialName("compaction")
    Compaction("compaction"),
    ;
  }
}
