package io.openai.model

import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement

/**
 * The output of a custom tool call from your code, being sent back to the model.
 *
 */
@Serializable
public data class CustomToolCallOutput(
  public val type: Type,
  public val id: String? = null,
  @SerialName("call_id")
  public val callId: String,
  public val output: Output,
) {
  /**
   * The output from the custom tool call generated by your code.
   * Can be a string or an list of output content.
   *
   */
  @Serializable(with = Output.Serializer::class)
  public sealed interface Output {
    @Serializable
    @JvmInline
    public value class CaseString(
      public val `value`: String,
    ) : Output

    @Serializable
    @JvmInline
    public value class CaseFunctionAndCustomToolCallOutputList(
      public val `value`: List<FunctionAndCustomToolCallOutput>,
    ) : Output

    public object Serializer : KSerializer<Output> {
      @OptIn(
        InternalSerializationApi::class,
        ExperimentalSerializationApi::class,
      )
      override val descriptor: SerialDescriptor =
          buildSerialDescriptor("io.openai.model.CustomToolCallOutput.Output", PolymorphicKind.SEALED) {
        element("CaseString", String.serializer().descriptor)
        element("CaseFunctionAndCustomToolCallOutputList", ListSerializer(FunctionAndCustomToolCallOutput.serializer()).descriptor)
      }

      override fun deserialize(decoder: Decoder): Output {
        val value = decoder.decodeSerializableValue(JsonElement.serializer())
        val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
        return json.attemptDeserialize(
          value,
          CaseFunctionAndCustomToolCallOutputList::class to { CaseFunctionAndCustomToolCallOutputList(decodeFromJsonElement(ListSerializer(FunctionAndCustomToolCallOutput.serializer()), it)) },
          CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
        )
      }

      override fun serialize(encoder: Encoder, `value`: Output) {
        when(value) {
          is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
          is CaseFunctionAndCustomToolCallOutputList -> encoder.encodeSerializableValue(ListSerializer(FunctionAndCustomToolCallOutput.serializer()), value.value)
        }
      }
    }
  }

  @Serializable
  public enum class Type(
    public val `value`: String,
  ) {
    @SerialName("custom_tool_call_output")
    CustomToolCallOutput("custom_tool_call_output"),
    ;
  }
}
