package io.openai.model

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the content or the URL of an image generated by the OpenAI API.
 */
@Serializable
public data class Image(
  @SerialName("b64_json")
  public val b64Json: String? = null,
  public val url: String? = null,
  @SerialName("revised_prompt")
  public val revisedPrompt: String? = null,
)
