package io.openai.model

import kotlin.OptIn
import kotlin.String
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement

@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator("type")
@Serializable
public sealed interface InputItem {
  /**
   * A message input to the model with a role indicating instruction following
   * hierarchy. Instructions given with the `developer` or `system` role take
   * precedence over instructions given with the `user` role. Messages with the
   * `assistant` role are presumed to have been generated by the model in previous
   * interactions.
   *
   */
  @SerialName("message")
  @Serializable
  public data class Message(
    public val role: Role,
    public val content: Content,
    public val phase: MessagePhase? = null,
  ) : InputItem {
    /**
     * Text, image, or audio input to the model, used to generate a response.
     * Can also contain previous assistant responses.
     *
     */
    @Serializable(with = Content.Serializer::class)
    public sealed interface Content {
      @Serializable
      @JvmInline
      public value class CaseString(
        public val `value`: String,
      ) : Content

      @Serializable
      @JvmInline
      public value class CaseInputMessageContentList(
        public val `value`: InputMessageContentList,
      ) : Content

      public object Serializer : KSerializer<Content> {
        @OptIn(
          InternalSerializationApi::class,
          ExperimentalSerializationApi::class,
        )
        override val descriptor: SerialDescriptor =
            buildSerialDescriptor("io.openai.model.InputItem.Message.Content", PolymorphicKind.SEALED) {
          element("CaseString", String.serializer().descriptor)
          element("CaseInputMessageContentList", InputMessageContentList.serializer().descriptor)
        }

        override fun deserialize(decoder: Decoder): Content {
          val value = decoder.decodeSerializableValue(JsonElement.serializer())
          val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
          return json.attemptDeserialize(
            value,
            CaseInputMessageContentList::class to { CaseInputMessageContentList(decodeFromJsonElement(InputMessageContentList.serializer(), it)) },
            CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
          )
        }

        override fun serialize(encoder: Encoder, `value`: Content) {
          when(value) {
            is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
            is CaseInputMessageContentList -> encoder.encodeSerializableValue(InputMessageContentList.serializer(), value.value)
          }
        }
      }
    }

    @Serializable
    public enum class Role(
      public val `value`: String,
    ) {
      @SerialName("user")
      User("user"),
      @SerialName("assistant")
      Assistant("assistant"),
      @SerialName("system")
      System("system"),
      @SerialName("developer")
      Developer("developer"),
      ;
    }
  }

  @Serializable
  @JvmInline
  @SerialName("Item")
  public value class Item(
    public val `value`: JsonElement,
  ) : InputItem

  /**
   * An internal identifier for an item to reference.
   */
  @SerialName("ItemReferenceParam")
  @Serializable
  public data class ItemReferenceParam(
    public val type: Type? = null,
    public val id: String,
  ) : InputItem {
    @Serializable
    public enum class Type(
      public val `value`: String,
    ) {
      @SerialName("item_reference")
      ItemReference("item_reference"),
      ;
    }
  }
}
