name = "coder"
description = "Write"
model = "gpt-5.4-mini"
model_reasoning_effort = "xhigh"
sandbox_mode = "workspace-write"
developer_instructions = """
Implement the next task in plans/PLAN.md, make sure to write tests for the new code you're adding.
When you're finished use the Gradle MCP to build the project.
"""
nickname_candidates = ["Codezor", "Coderina", "Codester"]