package io.openai.model

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class AuditLogEventType(
  public val `value`: String,
) {
  @SerialName("api_key.created")
  ApiKeyCreated("api_key.created"),
  @SerialName("api_key.updated")
  ApiKeyUpdated("api_key.updated"),
  @SerialName("api_key.deleted")
  ApiKeyDeleted("api_key.deleted"),
  @SerialName("certificate.created")
  CertificateCreated("certificate.created"),
  @SerialName("certificate.updated")
  CertificateUpdated("certificate.updated"),
  @SerialName("certificate.deleted")
  CertificateDeleted("certificate.deleted"),
  @SerialName("certificates.activated")
  CertificatesActivated("certificates.activated"),
  @SerialName("certificates.deactivated")
  CertificatesDeactivated("certificates.deactivated"),
  @SerialName("checkpoint.permission.created")
  CheckpointPermissionCreated("checkpoint.permission.created"),
  @SerialName("checkpoint.permission.deleted")
  CheckpointPermissionDeleted("checkpoint.permission.deleted"),
  @SerialName("external_key.registered")
  ExternalKeyRegistered("external_key.registered"),
  @SerialName("external_key.removed")
  ExternalKeyRemoved("external_key.removed"),
  @SerialName("group.created")
  GroupCreated("group.created"),
  @SerialName("group.updated")
  GroupUpdated("group.updated"),
  @SerialName("group.deleted")
  GroupDeleted("group.deleted"),
  @SerialName("invite.sent")
  InviteSent("invite.sent"),
  @SerialName("invite.accepted")
  InviteAccepted("invite.accepted"),
  @SerialName("invite.deleted")
  InviteDeleted("invite.deleted"),
  @SerialName("ip_allowlist.created")
  IpAllowlistCreated("ip_allowlist.created"),
  @SerialName("ip_allowlist.updated")
  IpAllowlistUpdated("ip_allowlist.updated"),
  @SerialName("ip_allowlist.deleted")
  IpAllowlistDeleted("ip_allowlist.deleted"),
  @SerialName("ip_allowlist.config.activated")
  IpAllowlistConfigActivated("ip_allowlist.config.activated"),
  @SerialName("ip_allowlist.config.deactivated")
  IpAllowlistConfigDeactivated("ip_allowlist.config.deactivated"),
  @SerialName("login.succeeded")
  LoginSucceeded("login.succeeded"),
  @SerialName("login.failed")
  LoginFailed("login.failed"),
  @SerialName("logout.succeeded")
  LogoutSucceeded("logout.succeeded"),
  @SerialName("logout.failed")
  LogoutFailed("logout.failed"),
  @SerialName("organization.updated")
  OrganizationUpdated("organization.updated"),
  @SerialName("project.created")
  ProjectCreated("project.created"),
  @SerialName("project.updated")
  ProjectUpdated("project.updated"),
  @SerialName("project.archived")
  ProjectArchived("project.archived"),
  @SerialName("project.deleted")
  ProjectDeleted("project.deleted"),
  @SerialName("rate_limit.updated")
  RateLimitUpdated("rate_limit.updated"),
  @SerialName("rate_limit.deleted")
  RateLimitDeleted("rate_limit.deleted"),
  @SerialName("resource.deleted")
  ResourceDeleted("resource.deleted"),
  @SerialName("tunnel.created")
  TunnelCreated("tunnel.created"),
  @SerialName("tunnel.updated")
  TunnelUpdated("tunnel.updated"),
  @SerialName("tunnel.deleted")
  TunnelDeleted("tunnel.deleted"),
  @SerialName("role.created")
  RoleCreated("role.created"),
  @SerialName("role.updated")
  RoleUpdated("role.updated"),
  @SerialName("role.deleted")
  RoleDeleted("role.deleted"),
  @SerialName("role.assignment.created")
  RoleAssignmentCreated("role.assignment.created"),
  @SerialName("role.assignment.deleted")
  RoleAssignmentDeleted("role.assignment.deleted"),
  @SerialName("scim.enabled")
  ScimEnabled("scim.enabled"),
  @SerialName("scim.disabled")
  ScimDisabled("scim.disabled"),
  @SerialName("service_account.created")
  ServiceAccountCreated("service_account.created"),
  @SerialName("service_account.updated")
  ServiceAccountUpdated("service_account.updated"),
  @SerialName("service_account.deleted")
  ServiceAccountDeleted("service_account.deleted"),
  @SerialName("user.added")
  UserAdded("user.added"),
  @SerialName("user.updated")
  UserUpdated("user.updated"),
  @SerialName("user.deleted")
  UserDeleted("user.deleted"),
  ;
}
