package io.openai.model

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A chat completion delta generated by streamed model responses.
 */
@Serializable
public data class ChatCompletionStreamResponseDelta(
  public val content: String? = null,
  @SerialName("function_call")
  public val functionCall: FunctionCall? = null,
  @SerialName("tool_calls")
  public val toolCalls: List<ChatCompletionMessageToolCallChunk>? = null,
  public val role: Role? = null,
  public val refusal: String? = null,
) {
  /**
   * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
   */
  @Serializable
  public data class FunctionCall(
    public val arguments: String? = null,
    public val name: String? = null,
  )

  @Serializable
  public enum class Role(
    public val `value`: String,
  ) {
    @SerialName("developer")
    Developer("developer"),
    @SerialName("system")
    System("system"),
    @SerialName("user")
    User("user"),
    @SerialName("assistant")
    Assistant("assistant"),
    @SerialName("tool")
    Tool("tool"),
    ;
  }
}
