package io.openai.model

import kotlin.Boolean
import kotlin.Double
import kotlin.Long
import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

@Serializable
public data class CreateEvalRunRequest(
  public val name: String? = null,
  public val metadata: Metadata? = null,
  @SerialName("data_source")
  public val dataSource: DataSource,
) {
  /**
   * Details about the run's data source.
   */
  @OptIn(ExperimentalSerializationApi::class)
  @JsonClassDiscriminator("type")
  @Serializable
  public sealed interface DataSource {
    /**
     * A JsonlRunDataSource object with that specifies a JSONL file that matches the eval 
     *
     */
    @JvmInline
    @SerialName("jsonl")
    @Serializable
    public value class Jsonl(
      public val source: Source,
    ) : DataSource {
      /**
       * Determines what populates the `item` namespace in the data source.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Source {
        @JvmInline
        @SerialName("file_content")
        @Serializable
        public value class FileContent(
          public val content: List<Content>,
        ) : Source {
          @Serializable
          public data class Content(
            public val item: JsonElement,
            public val sample: JsonElement? = null,
          )
        }

        @JvmInline
        @SerialName("file_id")
        @Serializable
        public value class FileId(
          public val id: String,
        ) : Source
      }
    }

    /**
     * A CompletionsRunDataSource object describing a model sampling configuration.
     *
     */
    @SerialName("completions")
    @Serializable
    public data class Completions(
      @SerialName("input_messages")
      public val inputMessages: InputMessages? = null,
      @SerialName("sampling_params")
      public val samplingParams: SamplingParams? = null,
      public val model: String? = null,
      public val source: Source,
    ) : DataSource {
      /**
       * Used when sampling from a model. Dictates the structure of the messages passed into the model. Can either be a reference to a prebuilt trajectory (ie, `item.input_trajectory`), or a template with variable references to the `item` namespace.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface InputMessages {
        @JvmInline
        @SerialName("template")
        @Serializable
        public value class Template(
          public val template: List<Template>,
        ) : InputMessages {
          @Serializable(with = Template.Serializer::class)
          public sealed interface Template {
            /**
             * A message input to the model with a role indicating instruction following
             * hierarchy. Instructions given with the `developer` or `system` role take
             * precedence over instructions given with the `user` role. Messages with the
             * `assistant` role are presumed to have been generated by the model in previous
             * interactions.
             *
             */
            @Serializable
            public data class EasyInputMessage(
              public val role: Role,
              public val content: Content,
              public val phase: MessagePhase? = null,
              public val type: Type? = null,
            ) : Template {
              /**
               * Text, image, or audio input to the model, used to generate a response.
               * Can also contain previous assistant responses.
               *
               */
              @Serializable(with = Content.Serializer::class)
              public sealed interface Content {
                @Serializable
                @JvmInline
                public value class CaseString(
                  public val `value`: String,
                ) : Content

                @Serializable
                @JvmInline
                public value class CaseInputMessageContentList(
                  public val `value`: InputMessageContentList,
                ) : Content

                public object Serializer : KSerializer<Content> {
                  @OptIn(
                    InternalSerializationApi::class,
                    ExperimentalSerializationApi::class,
                  )
                  override val descriptor: SerialDescriptor =
                      buildSerialDescriptor("io.openai.model.CreateEvalRunRequest.DataSource.Completions.InputMessages.Template.Template.EasyInputMessage.Content", PolymorphicKind.SEALED) {
                    element("CaseString", String.serializer().descriptor)
                    element("CaseInputMessageContentList", InputMessageContentList.serializer().descriptor)
                  }

                  override fun deserialize(decoder: Decoder): Content {
                    val value = decoder.decodeSerializableValue(JsonElement.serializer())
                    val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
                    return json.attemptDeserialize(
                      value,
                      CaseInputMessageContentList::class to { CaseInputMessageContentList(decodeFromJsonElement(InputMessageContentList.serializer(), it)) },
                      CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
                    )
                  }

                  override fun serialize(encoder: Encoder, `value`: Content) {
                    when(value) {
                      is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
                      is CaseInputMessageContentList -> encoder.encodeSerializableValue(InputMessageContentList.serializer(), value.value)
                    }
                  }
                }
              }

              @Serializable
              public enum class Role(
                public val `value`: String,
              ) {
                @SerialName("user")
                User("user"),
                @SerialName("assistant")
                Assistant("assistant"),
                @SerialName("system")
                System("system"),
                @SerialName("developer")
                Developer("developer"),
                ;
              }

              @Serializable
              public enum class Type(
                public val `value`: String,
              ) {
                @SerialName("message")
                Message("message"),
                ;
              }
            }

            /**
             * A message input to the model with a role indicating instruction following
             * hierarchy. Instructions given with the `developer` or `system` role take
             * precedence over instructions given with the `user` role. Messages with the
             * `assistant` role are presumed to have been generated by the model in previous
             * interactions.
             *
             */
            @Serializable
            public data class EvalItem(
              public val role: Role,
              public val content: EvalItemContent,
              public val type: Type? = null,
            ) : Template {
              @Serializable
              public enum class Role(
                public val `value`: String,
              ) {
                @SerialName("user")
                User("user"),
                @SerialName("assistant")
                Assistant("assistant"),
                @SerialName("system")
                System("system"),
                @SerialName("developer")
                Developer("developer"),
                ;
              }

              @Serializable
              public enum class Type(
                public val `value`: String,
              ) {
                @SerialName("message")
                Message("message"),
                ;
              }
            }

            public object Serializer : KSerializer<Template> {
              @OptIn(
                InternalSerializationApi::class,
                ExperimentalSerializationApi::class,
              )
              override val descriptor: SerialDescriptor =
                  buildSerialDescriptor("io.openai.model.CreateEvalRunRequest.DataSource.Completions.InputMessages.Template.Template", PolymorphicKind.SEALED) {
                element("EasyInputMessage", EasyInputMessage.serializer().descriptor)
                element("EvalItem", EvalItem.serializer().descriptor)
              }

              override fun deserialize(decoder: Decoder): Template {
                val value = decoder.decodeSerializableValue(JsonElement.serializer())
                val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
                val obj = value as? JsonObject
                val tag = (obj?.get("role") as? JsonPrimitive)?.content
                when(tag) {
                  "user" -> {
                    val keys = obj?.keys.orEmpty()
                    if ("phase" in keys) {
                      return json.decodeFromJsonElement(EasyInputMessage.serializer(), value)
                    }
                    return json.attemptDeserialize(
                      value,
                      EasyInputMessage::class to { decodeFromJsonElement(EasyInputMessage.serializer(), it) },
                      EvalItem::class to { decodeFromJsonElement(EvalItem.serializer(), it) },
                    )
                  }
                  "assistant" -> {
                    val keys = obj?.keys.orEmpty()
                    if ("phase" in keys) {
                      return json.decodeFromJsonElement(EasyInputMessage.serializer(), value)
                    }
                    return json.attemptDeserialize(
                      value,
                      EasyInputMessage::class to { decodeFromJsonElement(EasyInputMessage.serializer(), it) },
                      EvalItem::class to { decodeFromJsonElement(EvalItem.serializer(), it) },
                    )
                  }
                  "system" -> {
                    val keys = obj?.keys.orEmpty()
                    if ("phase" in keys) {
                      return json.decodeFromJsonElement(EasyInputMessage.serializer(), value)
                    }
                    return json.attemptDeserialize(
                      value,
                      EasyInputMessage::class to { decodeFromJsonElement(EasyInputMessage.serializer(), it) },
                      EvalItem::class to { decodeFromJsonElement(EvalItem.serializer(), it) },
                    )
                  }
                  "developer" -> {
                    val keys = obj?.keys.orEmpty()
                    if ("phase" in keys) {
                      return json.decodeFromJsonElement(EasyInputMessage.serializer(), value)
                    }
                    return json.attemptDeserialize(
                      value,
                      EasyInputMessage::class to { decodeFromJsonElement(EasyInputMessage.serializer(), it) },
                      EvalItem::class to { decodeFromJsonElement(EvalItem.serializer(), it) },
                    )
                  }
                  else -> throw SerializationException("Unknown tag: " + tag + " for io.openai.model.CreateEvalRunRequest.DataSource.Completions.InputMessages.Template.Template")
                }
              }

              override fun serialize(encoder: Encoder, `value`: Template) {
                when(value) {
                  is EasyInputMessage -> encoder.encodeSerializableValue(EasyInputMessage.serializer(), value)
                  is EvalItem -> encoder.encodeSerializableValue(EvalItem.serializer(), value)
                }
              }
            }
          }
        }

        @JvmInline
        @SerialName("item_reference")
        @Serializable
        public value class ItemReference(
          @SerialName("item_reference")
          public val itemReference: String,
        ) : InputMessages
      }

      @Serializable
      public data class SamplingParams(
        @SerialName("reasoning_effort")
        public val reasoningEffort: ReasoningEffort? = null,
        public val temperature: Double? = null,
        @SerialName("max_completion_tokens")
        public val maxCompletionTokens: Long? = null,
        @SerialName("top_p")
        public val topP: Double? = null,
        public val seed: Long? = null,
        @SerialName("response_format")
        public val responseFormat: ResponseFormat? = null,
        public val tools: List<ChatCompletionTool>? = null,
      ) {
        /**
         * An object specifying the format that the model must output.
         *
         * Setting to `{ "type": "json_schema", "json_schema": {...} }` enables
         * Structured Outputs which ensures the model will match your supplied JSON
         * schema. Learn more in the [Structured Outputs
         * guide](/docs/guides/structured-outputs).
         *
         * Setting to `{ "type": "json_object" }` enables the older JSON mode, which
         * ensures the message the model generates is valid JSON. Using `json_schema`
         * is preferred for models that support it.
         *
         */
        @OptIn(ExperimentalSerializationApi::class)
        @JsonClassDiscriminator("type")
        @Serializable
        public sealed interface ResponseFormat {
          @Serializable
          @SerialName("text")
          public data object Text : ResponseFormat

          /**
           * JSON Schema response format. Used to generate structured JSON responses.
           * Learn more about [Structured Outputs](/docs/guides/structured-outputs).
           *
           */
          @SerialName("json_schema")
          @Serializable
          public data class JsonSchema(
            public val description: String? = null,
            public val name: String,
            public val schema: ResponseFormatJsonSchemaSchema? = null,
            public val strict: Boolean? = null,
          ) : ResponseFormat

          @Serializable
          @SerialName("json_object")
          public data object JsonObject : ResponseFormat
        }
      }

      /**
       * Determines what populates the `item` namespace in this run's data source.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Source {
        @JvmInline
        @SerialName("file_content")
        @Serializable
        public value class FileContent(
          public val content: List<Content>,
        ) : Source {
          @Serializable
          public data class Content(
            public val item: JsonElement,
            public val sample: JsonElement? = null,
          )
        }

        @JvmInline
        @SerialName("file_id")
        @Serializable
        public value class FileId(
          public val id: String,
        ) : Source

        /**
         * A StoredCompletionsRunDataSource configuration describing a set of filters
         *
         */
        @SerialName("stored_completions")
        @Serializable
        public data class StoredCompletions(
          public val metadata: Metadata? = null,
          public val model: String? = null,
          @SerialName("created_after")
          public val createdAfter: Long? = null,
          @SerialName("created_before")
          public val createdBefore: Long? = null,
          public val limit: Long? = null,
        ) : Source
      }
    }

    /**
     * A ResponsesRunDataSource object describing a model sampling configuration.
     *
     */
    @SerialName("responses")
    @Serializable
    public data class Responses(
      @SerialName("input_messages")
      public val inputMessages: InputMessages? = null,
      @SerialName("sampling_params")
      public val samplingParams: SamplingParams? = null,
      public val model: String? = null,
      public val source: Source,
    ) : DataSource {
      /**
       * Used when sampling from a model. Dictates the structure of the messages passed into the model. Can either be a reference to a prebuilt trajectory (ie, `item.input_trajectory`), or a template with variable references to the `item` namespace.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface InputMessages {
        @JvmInline
        @SerialName("template")
        @Serializable
        public value class Template(
          public val template: List<Template>,
        ) : InputMessages {
          @Serializable(with = Template.Serializer::class)
          public sealed interface Template {
            @Serializable
            public data class CaseElse(
              public val role: String,
              public val content: String,
            ) : Template

            @Serializable
            @JvmInline
            public value class CaseEvalItem(
              public val `value`: EvalItem,
            ) : Template

            public object Serializer : KSerializer<Template> {
              @OptIn(
                InternalSerializationApi::class,
                ExperimentalSerializationApi::class,
              )
              override val descriptor: SerialDescriptor =
                  buildSerialDescriptor("io.openai.model.CreateEvalRunRequest.DataSource.Responses.InputMessages.Template.Template", PolymorphicKind.SEALED) {
                element("CaseElse", CaseElse.serializer().descriptor)
                element("CaseEvalItem", EvalItem.serializer().descriptor)
              }

              override fun deserialize(decoder: Decoder): Template {
                val value = decoder.decodeSerializableValue(JsonElement.serializer())
                val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
                return json.attemptDeserialize(
                  value,
                  CaseElse::class to { decodeFromJsonElement(CaseElse.serializer(), it) },
                  CaseEvalItem::class to { CaseEvalItem(decodeFromJsonElement(EvalItem.serializer(), it)) },
                )
              }

              override fun serialize(encoder: Encoder, `value`: Template) {
                when(value) {
                  is CaseElse -> encoder.encodeSerializableValue(CaseElse.serializer(), value)
                  is CaseEvalItem -> encoder.encodeSerializableValue(EvalItem.serializer(), value.value)
                }
              }
            }
          }
        }

        @JvmInline
        @SerialName("item_reference")
        @Serializable
        public value class ItemReference(
          @SerialName("item_reference")
          public val itemReference: String,
        ) : InputMessages
      }

      @Serializable
      public data class SamplingParams(
        @SerialName("reasoning_effort")
        public val reasoningEffort: ReasoningEffort? = null,
        public val temperature: Double? = null,
        @SerialName("max_completion_tokens")
        public val maxCompletionTokens: Long? = null,
        @SerialName("top_p")
        public val topP: Double? = null,
        public val seed: Long? = null,
        public val tools: List<Tool>? = null,
        public val text: Text? = null,
      ) {
        /**
         * Configuration options for a text response from the model. Can be plain
         * text or structured JSON data. Learn more:
         * - [Text inputs and outputs](/docs/guides/text)
         * - [Structured Outputs](/docs/guides/structured-outputs)
         *
         */
        @JvmInline
        @Serializable
        public value class Text(
          public val format: TextResponseFormatConfiguration? = null,
        )
      }

      /**
       * Determines what populates the `item` namespace in this run's data source.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Source {
        @JvmInline
        @SerialName("file_content")
        @Serializable
        public value class FileContent(
          public val content: List<Content>,
        ) : Source {
          @Serializable
          public data class Content(
            public val item: JsonElement,
            public val sample: JsonElement? = null,
          )
        }

        @JvmInline
        @SerialName("file_id")
        @Serializable
        public value class FileId(
          public val id: String,
        ) : Source

        /**
         * A EvalResponsesSource object describing a run data source configuration.
         *
         */
        @SerialName("responses")
        @Serializable
        public data class Responses(
          public val metadata: JsonElement? = null,
          public val model: String? = null,
          @SerialName("instructions_search")
          public val instructionsSearch: String? = null,
          @SerialName("created_after")
          public val createdAfter: Long? = null,
          @SerialName("created_before")
          public val createdBefore: Long? = null,
          @SerialName("reasoning_effort")
          public val reasoningEffort: ReasoningEffort? = null,
          public val temperature: Double? = null,
          @SerialName("top_p")
          public val topP: Double? = null,
          public val users: List<String>? = null,
          public val tools: List<String>? = null,
        ) : Source
      }
    }
  }
}
