package io.openai.model

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A message input to the model with a role indicating instruction following
 * hierarchy. Instructions given with the `developer` or `system` role take
 * precedence over instructions given with the `user` role. Messages with the
 * `assistant` role are presumed to have been generated by the model in previous
 * interactions.
 *
 */
@Serializable
public data class EvalItem(
  public val role: Role,
  public val content: EvalItemContent,
  public val type: Type? = null,
) {
  @Serializable
  public enum class Role(
    public val `value`: String,
  ) {
    @SerialName("user")
    User("user"),
    @SerialName("assistant")
    Assistant("assistant"),
    @SerialName("system")
    System("system"),
    @SerialName("developer")
    Developer("developer"),
    ;
  }

  @Serializable
  public enum class Type(
    public val `value`: String,
  ) {
    @SerialName("message")
    Message("message"),
    ;
  }
}
