package io.openai.model

import kotlin.Boolean
import kotlin.Float
import kotlin.Long
import kotlin.OptIn
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmInline
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

@Serializable(with = InputItem.Serializer::class)
public sealed interface InputItem {
  /**
   * A message input to the model with a role indicating instruction following
   * hierarchy. Instructions given with the `developer` or `system` role take
   * precedence over instructions given with the `user` role. Messages with the
   * `assistant` role are presumed to have been generated by the model in previous
   * interactions.
   *
   */
  @Serializable
  public data class Message(
    public val role: Role,
    public val content: Content,
    public val phase: MessagePhase? = null,
    public val type: Type? = null,
  ) : InputItem {
    /**
     * Text, image, or audio input to the model, used to generate a response.
     * Can also contain previous assistant responses.
     *
     */
    @Serializable(with = Content.Serializer::class)
    public sealed interface Content {
      @Serializable
      @JvmInline
      public value class CaseString(
        public val `value`: String,
      ) : Content

      @Serializable
      @JvmInline
      public value class CaseInputMessageContentList(
        public val `value`: InputMessageContentList,
      ) : Content

      public object Serializer : KSerializer<Content> {
        @OptIn(
          InternalSerializationApi::class,
          ExperimentalSerializationApi::class,
        )
        override val descriptor: SerialDescriptor =
            buildSerialDescriptor("io.openai.model.InputItem.Message.Content", PolymorphicKind.SEALED) {
          element("CaseString", String.serializer().descriptor)
          element("CaseInputMessageContentList", InputMessageContentList.serializer().descriptor)
        }

        override fun deserialize(decoder: Decoder): Content {
          val value = decoder.decodeSerializableValue(JsonElement.serializer())
          val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
          return json.attemptDeserialize(
            value,
            CaseInputMessageContentList::class to { CaseInputMessageContentList(decodeFromJsonElement(InputMessageContentList.serializer(), it)) },
            CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
          )
        }

        override fun serialize(encoder: Encoder, `value`: Content) {
          when(value) {
            is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
            is CaseInputMessageContentList -> encoder.encodeSerializableValue(InputMessageContentList.serializer(), value.value)
          }
        }
      }
    }

    @Serializable
    public enum class Role(
      public val `value`: String,
    ) {
      @SerialName("user")
      User("user"),
      @SerialName("assistant")
      Assistant("assistant"),
      @SerialName("system")
      System("system"),
      @SerialName("developer")
      Developer("developer"),
      ;
    }

    @Serializable
    public enum class Type(
      public val `value`: String,
    ) {
      @SerialName("message")
      Message("message"),
      ;
    }
  }

  /**
   * Content item used to generate a response.
   *
   */
  @Serializable(with = Item.Serializer::class)
  public sealed interface Item : InputItem {
    /**
     * A message input to the model with a role indicating instruction following
     * hierarchy. Instructions given with the `developer` or `system` role take
     * precedence over instructions given with the `user` role.
     *
     */
    @Serializable
    public data class InputMessage(
      public val type: Type? = null,
      public val role: Role,
      public val status: Status? = null,
      public val content: InputMessageContentList,
    ) : Item {
      @Serializable
      public enum class Role(
        public val `value`: String,
      ) {
        @SerialName("user")
        User("user"),
        @SerialName("system")
        System("system"),
        @SerialName("developer")
        Developer("developer"),
        ;
      }

      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("message")
        Message("message"),
        ;
      }
    }

    /**
     * An output message from the model.
     *
     */
    @Serializable
    public data class OutputMessage(
      public val id: String,
      public val type: Type,
      public val role: Role,
      public val content: List<OutputMessageContent>,
      public val phase: MessagePhase? = null,
      public val status: Status,
    ) : Item {
      @Serializable
      public enum class Role(
        public val `value`: String,
      ) {
        @SerialName("assistant")
        Assistant("assistant"),
        ;
      }

      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("message")
        Message("message"),
        ;
      }
    }

    /**
     * The results of a file search tool call. See the
     * [file search guide](/docs/guides/tools-file-search) for more information.
     *
     */
    @Serializable
    public data class FileSearchCall(
      public val id: String,
      public val type: Type,
      public val status: Status,
      public val queries: List<String>,
      public val results: List<Results>? = null,
    ) : Item {
      @Serializable
      public data class Results(
        @SerialName("file_id")
        public val fileId: String? = null,
        public val text: String? = null,
        public val filename: String? = null,
        public val attributes: VectorStoreFileAttributes? = null,
        public val score: Float? = null,
      )

      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("searching")
        Searching("searching"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        @SerialName("failed")
        Failed("failed"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("file_search_call")
        FileSearchCall("file_search_call"),
        ;
      }
    }

    /**
     * A tool call to a computer use tool. See the
     * [computer use guide](/docs/guides/tools-computer-use) for more information.
     *
     */
    @Serializable
    public data class ComputerCall(
      @Required
      public val type: Type = Type.ComputerCall,
      public val id: String,
      @SerialName("call_id")
      public val callId: String,
      public val action: ComputerAction? = null,
      public val actions: ComputerActionList? = null,
      @SerialName("pending_safety_checks")
      public val pendingSafetyChecks: List<ComputerCallSafetyCheckParam>,
      public val status: Status,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("computer_call")
        ComputerCall("computer_call"),
        ;
      }
    }

    /**
     * The output of a computer tool call.
     */
    @Serializable
    public data class ComputerCallOutput(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      @Required
      public val type: Type = Type.ComputerCallOutput,
      public val output: ComputerScreenshotImage,
      @SerialName("acknowledged_safety_checks")
      public val acknowledgedSafetyChecks: List<ComputerCallSafetyCheckParam>? = null,
      public val status: FunctionCallItemStatus? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("computer_call_output")
        ComputerCallOutput("computer_call_output"),
        ;
      }
    }

    /**
     * The results of a web search tool call. See the
     * [web search guide](/docs/guides/tools-web-search) for more information.
     *
     */
    @Serializable
    public data class WebSearchCall(
      public val id: String,
      public val type: Type,
      public val status: Status,
      public val action: Action,
    ) : Item {
      /**
       * An object describing the specific action taken in this web search call.
       * Includes details on how the model used the web (search, open_page, find_in_page).
       *
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Action {
        /**
         * Action type "search" - Performs a web search query.
         *
         */
        @SerialName("search")
        @Serializable
        public data class Search(
          public val query: String,
          public val queries: List<String>? = null,
          public val sources: List<Sources>? = null,
        ) : Action {
          /**
           * A source used in the search.
           *
           */
          @Serializable
          public data class Sources(
            public val type: Type,
            public val url: String,
          ) {
            @Serializable
            public enum class Type(
              public val `value`: String,
            ) {
              @SerialName("url")
              Url("url"),
              ;
            }
          }
        }

        /**
         * Action type "open_page" - Opens a specific URL from search results.
         *
         */
        @JvmInline
        @SerialName("open_page")
        @Serializable
        public value class OpenPage(
          public val url: String? = null,
        ) : Action

        /**
         * Action type "find_in_page": Searches for a pattern within a loaded page.
         *
         */
        @SerialName("find_in_page")
        @Serializable
        public data class FindInPage(
          public val url: String,
          public val pattern: String,
        ) : Action
      }

      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("searching")
        Searching("searching"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("failed")
        Failed("failed"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("web_search_call")
        WebSearchCall("web_search_call"),
        ;
      }
    }

    /**
     * A tool call to run a function. See the 
     * [function calling guide](/docs/guides/function-calling) for more information.
     *
     */
    @Serializable
    public data class FunctionCall(
      public val id: String? = null,
      public val type: Type,
      @SerialName("call_id")
      public val callId: String,
      public val namespace: String? = null,
      public val name: String,
      public val arguments: String,
      public val status: Status? = null,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("function_call")
        FunctionCall("function_call"),
        ;
      }
    }

    /**
     * The output of a function tool call.
     */
    @Serializable
    public data class FunctionCallOutput(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      @Required
      public val type: Type = Type.FunctionCallOutput,
      public val output: Output,
      public val status: FunctionCallItemStatus? = null,
    ) : Item {
      /**
       * Text, image, or file output of the function tool call.
       */
      @Serializable(with = Output.Serializer::class)
      public sealed interface Output {
        @Serializable
        @JvmInline
        public value class CaseString(
          public val `value`: String,
        ) : Output

        @Serializable
        @JvmInline
        public value class CaseInputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParamList(
          public val `value`:
              List<InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam>,
        ) : Output

        /**
         * A piece of message content, such as text, an image, or a file.
         */
        @OptIn(ExperimentalSerializationApi::class)
        @JsonClassDiscriminator("type")
        @Serializable
        public sealed interface InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam {
          /**
           * A text input to the model.
           */
          @JvmInline
          @SerialName("input_text")
          @Serializable
          public value class InputText(
            public val text: String,
          ) : InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam

          /**
           * An image input to the model. Learn about [image inputs](/docs/guides/vision)
           */
          @SerialName("input_image")
          @Serializable
          public data class InputImage(
            @SerialName("image_url")
            public val imageUrl: String? = null,
            @SerialName("file_id")
            public val fileId: String? = null,
            public val detail: DetailEnum? = null,
          ) : InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam

          /**
           * A file input to the model.
           */
          @SerialName("input_file")
          @Serializable
          public data class InputFile(
            @SerialName("file_id")
            public val fileId: String? = null,
            public val filename: String? = null,
            @SerialName("file_data")
            public val fileData: String? = null,
            @SerialName("file_url")
            public val fileUrl: String? = null,
          ) : InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam
        }

        public object Serializer : KSerializer<Output> {
          @OptIn(
            InternalSerializationApi::class,
            ExperimentalSerializationApi::class,
          )
          override val descriptor: SerialDescriptor =
              buildSerialDescriptor("io.openai.model.InputItem.Item.FunctionCallOutput.Output", PolymorphicKind.SEALED) {
            element("CaseString", String.serializer().descriptor)
            element("CaseInputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParamList", ListSerializer(InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam.serializer()).descriptor)
          }

          override fun deserialize(decoder: Decoder): Output {
            val value = decoder.decodeSerializableValue(JsonElement.serializer())
            val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
            return json.attemptDeserialize(
              value,
              CaseInputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParamList::class to { CaseInputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParamList(decodeFromJsonElement(ListSerializer(InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam.serializer()), it)) },
              CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
            )
          }

          override fun serialize(encoder: Encoder, `value`: Output) {
            when(value) {
              is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
              is CaseInputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParamList -> encoder.encodeSerializableValue(ListSerializer(InputTextContentParamOrInputImageContentParamAutoParamOrInputFileContentParam.serializer()), value.value)
            }
          }
        }
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("function_call_output")
        FunctionCallOutput("function_call_output"),
        ;
      }
    }

    @Serializable
    public data class ToolSearchCall(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String? = null,
      @Required
      public val type: Type = Type.ToolSearchCall,
      public val execution: ToolSearchExecutionType? = null,
      public val arguments: EmptyModelParam,
      public val status: FunctionCallItemStatus? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("tool_search_call")
        ToolSearchCall("tool_search_call"),
        ;
      }
    }

    @Serializable
    public data class ToolSearchOutput(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String? = null,
      @Required
      public val type: Type = Type.ToolSearchOutput,
      public val execution: ToolSearchExecutionType? = null,
      public val tools: List<Tool>,
      public val status: FunctionCallItemStatus? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("tool_search_output")
        ToolSearchOutput("tool_search_output"),
        ;
      }
    }

    /**
     * A description of the chain of thought used by a reasoning model while generating
     * a response. Be sure to include these items in your `input` to the Responses API
     * for subsequent turns of a conversation if you are manually
     * [managing context](/docs/guides/conversation-state).
     *
     */
    @Serializable
    public data class Reasoning(
      public val type: Type,
      public val id: String,
      @SerialName("encrypted_content")
      public val encryptedContent: String? = null,
      public val summary: List<SummaryTextContent>,
      public val content: List<ReasoningTextContent>? = null,
      public val status: Status? = null,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("reasoning")
        Reasoning("reasoning"),
        ;
      }
    }

    /**
     * A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
     */
    @Serializable
    public data class Compaction(
      public val id: String? = null,
      @Required
      public val type: Type = Type.Compaction,
      @SerialName("encrypted_content")
      public val encryptedContent: String,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("compaction")
        Compaction("compaction"),
        ;
      }
    }

    /**
     * An image generation request made by the model.
     *
     */
    @Serializable
    public data class ImageGenerationCall(
      public val type: Type,
      public val id: String,
      public val status: Status,
      public val result: String?,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("generating")
        Generating("generating"),
        @SerialName("failed")
        Failed("failed"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("image_generation_call")
        ImageGenerationCall("image_generation_call"),
        ;
      }
    }

    /**
     * A tool call to run code.
     *
     */
    @Serializable
    public data class CodeInterpreterCall(
      @Required
      public val type: Type = Type.CodeInterpreterCall,
      public val id: String,
      public val status: Status,
      @SerialName("container_id")
      public val containerId: String,
      public val code: String?,
      public val outputs: List<Outputs>?,
    ) : Item {
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Outputs {
        /**
         * The logs output from the code interpreter.
         */
        @JvmInline
        @SerialName("logs")
        @Serializable
        public value class Logs(
          public val logs: String,
        ) : Outputs

        /**
         * The image output from the code interpreter.
         */
        @JvmInline
        @SerialName("image")
        @Serializable
        public value class Image(
          public val url: String,
        ) : Outputs
      }

      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        @SerialName("interpreting")
        Interpreting("interpreting"),
        @SerialName("failed")
        Failed("failed"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("code_interpreter_call")
        CodeInterpreterCall("code_interpreter_call"),
        ;
      }
    }

    /**
     * A tool call to run a command on the local shell.
     *
     */
    @Serializable
    public data class LocalShellCall(
      public val type: Type,
      public val id: String,
      @SerialName("call_id")
      public val callId: String,
      public val action: LocalShellExecAction,
      public val status: Status,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("local_shell_call")
        LocalShellCall("local_shell_call"),
        ;
      }
    }

    /**
     * The output of a local shell tool call.
     *
     */
    @Serializable
    public data class LocalShellCallOutput(
      public val type: Type,
      public val id: String,
      public val output: String,
      public val status: Status? = null,
    ) : Item {
      @Serializable
      public enum class Status(
        public val `value`: String,
      ) {
        @SerialName("in_progress")
        InProgress("in_progress"),
        @SerialName("completed")
        Completed("completed"),
        @SerialName("incomplete")
        Incomplete("incomplete"),
        ;
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("local_shell_call_output")
        LocalShellCallOutput("local_shell_call_output"),
        ;
      }
    }

    /**
     * A tool representing a request to execute one or more shell commands.
     */
    @Serializable
    public data class ShellCall(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      @Required
      public val type: Type = Type.ShellCall,
      public val action: FunctionShellActionParam,
      public val status: FunctionShellCallItemStatus? = null,
      public val environment: Environment? = null,
    ) : Item {
      /**
       * The environment to execute the shell commands in.
       */
      @OptIn(ExperimentalSerializationApi::class)
      @JsonClassDiscriminator("type")
      @Serializable
      public sealed interface Environment {
        @JvmInline
        @SerialName("local")
        @Serializable
        public value class Local(
          public val skills: List<LocalSkillParam>? = null,
        ) : Environment

        @JvmInline
        @SerialName("container_reference")
        @Serializable
        public value class ContainerReference(
          @SerialName("container_id")
          public val containerId: String,
        ) : Environment
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("shell_call")
        ShellCall("shell_call"),
        ;
      }
    }

    /**
     * The streamed output items emitted by a shell tool call.
     */
    @Serializable
    public data class ShellCallOutput(
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      @Required
      public val type: Type = Type.ShellCallOutput,
      public val output: List<FunctionShellCallOutputContentParam>,
      public val status: FunctionShellCallItemStatus? = null,
      @SerialName("max_output_length")
      public val maxOutputLength: Long? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("shell_call_output")
        ShellCallOutput("shell_call_output"),
        ;
      }
    }

    /**
     * A tool call representing a request to create, delete, or update files using diff patches.
     */
    @Serializable
    public data class ApplyPatchCall(
      @Required
      public val type: Type = Type.ApplyPatchCall,
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      public val status: ApplyPatchCallStatusParam,
      public val operation: ApplyPatchOperationParam,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("apply_patch_call")
        ApplyPatchCall("apply_patch_call"),
        ;
      }
    }

    /**
     * The streamed output emitted by an apply patch tool call.
     */
    @Serializable
    public data class ApplyPatchCallOutput(
      @Required
      public val type: Type = Type.ApplyPatchCallOutput,
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      public val status: ApplyPatchCallOutputStatusParam,
      public val output: String? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("apply_patch_call_output")
        ApplyPatchCallOutput("apply_patch_call_output"),
        ;
      }
    }

    /**
     * A list of tools available on an MCP server.
     *
     */
    @Serializable
    public data class McpListTools(
      public val type: Type,
      public val id: String,
      @SerialName("server_label")
      public val serverLabel: String,
      public val tools: List<MCPListToolsTool>,
      public val error: String? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("mcp_list_tools")
        McpListTools("mcp_list_tools"),
        ;
      }
    }

    /**
     * A request for human approval of a tool invocation.
     *
     */
    @Serializable
    public data class McpApprovalRequest(
      public val type: Type,
      public val id: String,
      @SerialName("server_label")
      public val serverLabel: String,
      public val name: String,
      public val arguments: String,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("mcp_approval_request")
        McpApprovalRequest("mcp_approval_request"),
        ;
      }
    }

    /**
     * A response to an MCP approval request.
     *
     */
    @Serializable
    public data class McpApprovalResponse(
      public val type: Type,
      public val id: String? = null,
      @SerialName("approval_request_id")
      public val approvalRequestId: String,
      public val approve: Boolean,
      public val reason: String? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("mcp_approval_response")
        McpApprovalResponse("mcp_approval_response"),
        ;
      }
    }

    /**
     * An invocation of a tool on an MCP server.
     *
     */
    @Serializable
    public data class McpCall(
      public val type: Type,
      public val id: String,
      @SerialName("server_label")
      public val serverLabel: String,
      public val name: String,
      public val arguments: String,
      public val output: String? = null,
      public val error: String? = null,
      public val status: MCPToolCallStatus? = null,
      @SerialName("approval_request_id")
      public val approvalRequestId: String? = null,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("mcp_call")
        McpCall("mcp_call"),
        ;
      }
    }

    /**
     * The output of a custom tool call from your code, being sent back to the model.
     *
     */
    @Serializable
    public data class CustomToolCallOutput(
      public val type: Type,
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      public val output: Output,
    ) : Item {
      /**
       * The output from the custom tool call generated by your code.
       * Can be a string or an list of output content.
       *
       */
      @Serializable(with = Output.Serializer::class)
      public sealed interface Output {
        @Serializable
        @JvmInline
        public value class CaseString(
          public val `value`: String,
        ) : Output

        @Serializable
        @JvmInline
        public value class CaseFunctionAndCustomToolCallOutputList(
          public val `value`: List<FunctionAndCustomToolCallOutput>,
        ) : Output

        public object Serializer : KSerializer<Output> {
          @OptIn(
            InternalSerializationApi::class,
            ExperimentalSerializationApi::class,
          )
          override val descriptor: SerialDescriptor =
              buildSerialDescriptor("io.openai.model.InputItem.Item.CustomToolCallOutput.Output", PolymorphicKind.SEALED) {
            element("CaseString", String.serializer().descriptor)
            element("CaseFunctionAndCustomToolCallOutputList", ListSerializer(FunctionAndCustomToolCallOutput.serializer()).descriptor)
          }

          override fun deserialize(decoder: Decoder): Output {
            val value = decoder.decodeSerializableValue(JsonElement.serializer())
            val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
            return json.attemptDeserialize(
              value,
              CaseFunctionAndCustomToolCallOutputList::class to { CaseFunctionAndCustomToolCallOutputList(decodeFromJsonElement(ListSerializer(FunctionAndCustomToolCallOutput.serializer()), it)) },
              CaseString::class to { CaseString(decodeFromJsonElement(String.serializer(), it)) },
            )
          }

          override fun serialize(encoder: Encoder, `value`: Output) {
            when(value) {
              is CaseString -> encoder.encodeSerializableValue(String.serializer(), value.value)
              is CaseFunctionAndCustomToolCallOutputList -> encoder.encodeSerializableValue(ListSerializer(FunctionAndCustomToolCallOutput.serializer()), value.value)
            }
          }
        }
      }

      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("custom_tool_call_output")
        CustomToolCallOutput("custom_tool_call_output"),
        ;
      }
    }

    /**
     * A call to a custom tool created by the model.
     *
     */
    @Serializable
    public data class CustomToolCall(
      public val type: Type,
      public val id: String? = null,
      @SerialName("call_id")
      public val callId: String,
      public val namespace: String? = null,
      public val name: String,
      public val input: String,
    ) : Item {
      @Serializable
      public enum class Type(
        public val `value`: String,
      ) {
        @SerialName("custom_tool_call")
        CustomToolCall("custom_tool_call"),
        ;
      }
    }

    public object Serializer : KSerializer<Item> {
      @OptIn(
        InternalSerializationApi::class,
        ExperimentalSerializationApi::class,
      )
      override val descriptor: SerialDescriptor =
          buildSerialDescriptor("io.openai.model.InputItem.Item", PolymorphicKind.SEALED) {
        element("InputMessage", InputMessage.serializer().descriptor)
        element("OutputMessage", OutputMessage.serializer().descriptor)
        element("FileSearchCall", FileSearchCall.serializer().descriptor)
        element("ComputerCall", ComputerCall.serializer().descriptor)
        element("ComputerCallOutput", ComputerCallOutput.serializer().descriptor)
        element("WebSearchCall", WebSearchCall.serializer().descriptor)
        element("FunctionCall", FunctionCall.serializer().descriptor)
        element("FunctionCallOutput", FunctionCallOutput.serializer().descriptor)
        element("ToolSearchCall", ToolSearchCall.serializer().descriptor)
        element("ToolSearchOutput", ToolSearchOutput.serializer().descriptor)
        element("Reasoning", Reasoning.serializer().descriptor)
        element("Compaction", Compaction.serializer().descriptor)
        element("ImageGenerationCall", ImageGenerationCall.serializer().descriptor)
        element("CodeInterpreterCall", CodeInterpreterCall.serializer().descriptor)
        element("LocalShellCall", LocalShellCall.serializer().descriptor)
        element("LocalShellCallOutput", LocalShellCallOutput.serializer().descriptor)
        element("ShellCall", ShellCall.serializer().descriptor)
        element("ShellCallOutput", ShellCallOutput.serializer().descriptor)
        element("ApplyPatchCall", ApplyPatchCall.serializer().descriptor)
        element("ApplyPatchCallOutput", ApplyPatchCallOutput.serializer().descriptor)
        element("McpListTools", McpListTools.serializer().descriptor)
        element("McpApprovalRequest", McpApprovalRequest.serializer().descriptor)
        element("McpApprovalResponse", McpApprovalResponse.serializer().descriptor)
        element("McpCall", McpCall.serializer().descriptor)
        element("CustomToolCallOutput", CustomToolCallOutput.serializer().descriptor)
        element("CustomToolCall", CustomToolCall.serializer().descriptor)
      }

      override fun deserialize(decoder: Decoder): Item {
        val value = decoder.decodeSerializableValue(JsonElement.serializer())
        val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
        val obj = value as? JsonObject
        val tag = (obj?.get("type") as? JsonPrimitive)?.content
        when(tag) {
          "file_search_call" -> return json.decodeFromJsonElement(FileSearchCall.serializer(), value)
          "computer_call" -> return json.decodeFromJsonElement(ComputerCall.serializer(), value)
          "computer_call_output" -> return json.decodeFromJsonElement(ComputerCallOutput.serializer(), value)
          "web_search_call" -> return json.decodeFromJsonElement(WebSearchCall.serializer(), value)
          "function_call" -> return json.decodeFromJsonElement(FunctionCall.serializer(), value)
          "function_call_output" -> return json.decodeFromJsonElement(FunctionCallOutput.serializer(), value)
          "tool_search_call" -> return json.decodeFromJsonElement(ToolSearchCall.serializer(), value)
          "tool_search_output" -> return json.decodeFromJsonElement(ToolSearchOutput.serializer(), value)
          "reasoning" -> return json.decodeFromJsonElement(Reasoning.serializer(), value)
          "compaction" -> return json.decodeFromJsonElement(Compaction.serializer(), value)
          "image_generation_call" -> return json.decodeFromJsonElement(ImageGenerationCall.serializer(), value)
          "code_interpreter_call" -> return json.decodeFromJsonElement(CodeInterpreterCall.serializer(), value)
          "local_shell_call" -> return json.decodeFromJsonElement(LocalShellCall.serializer(), value)
          "local_shell_call_output" -> return json.decodeFromJsonElement(LocalShellCallOutput.serializer(), value)
          "shell_call" -> return json.decodeFromJsonElement(ShellCall.serializer(), value)
          "shell_call_output" -> return json.decodeFromJsonElement(ShellCallOutput.serializer(), value)
          "apply_patch_call" -> return json.decodeFromJsonElement(ApplyPatchCall.serializer(), value)
          "apply_patch_call_output" -> return json.decodeFromJsonElement(ApplyPatchCallOutput.serializer(), value)
          "mcp_list_tools" -> return json.decodeFromJsonElement(McpListTools.serializer(), value)
          "mcp_approval_request" -> return json.decodeFromJsonElement(McpApprovalRequest.serializer(), value)
          "mcp_approval_response" -> return json.decodeFromJsonElement(McpApprovalResponse.serializer(), value)
          "mcp_call" -> return json.decodeFromJsonElement(McpCall.serializer(), value)
          "custom_tool_call_output" -> return json.decodeFromJsonElement(CustomToolCallOutput.serializer(), value)
          "custom_tool_call" -> return json.decodeFromJsonElement(CustomToolCall.serializer(), value)
          "message" -> {
            val keys = obj?.keys.orEmpty()
            if ("id" in keys || "phase" in keys) {
              return json.decodeFromJsonElement(OutputMessage.serializer(), value)
            }
            return json.attemptDeserialize(
              value,
              OutputMessage::class to { decodeFromJsonElement(OutputMessage.serializer(), it) },
              InputMessage::class to { decodeFromJsonElement(InputMessage.serializer(), it) },
            )
          }
          else -> throw SerializationException("Unknown tag: " + tag + " for io.openai.model.InputItem.Item")
        }
      }

      override fun serialize(encoder: Encoder, `value`: Item) {
        when(value) {
          is InputMessage -> encoder.encodeSerializableValue(InputMessage.serializer(), value)
          is OutputMessage -> encoder.encodeSerializableValue(OutputMessage.serializer(), value)
          is FileSearchCall -> encoder.encodeSerializableValue(FileSearchCall.serializer(), value)
          is ComputerCall -> encoder.encodeSerializableValue(ComputerCall.serializer(), value)
          is ComputerCallOutput -> encoder.encodeSerializableValue(ComputerCallOutput.serializer(), value)
          is WebSearchCall -> encoder.encodeSerializableValue(WebSearchCall.serializer(), value)
          is FunctionCall -> encoder.encodeSerializableValue(FunctionCall.serializer(), value)
          is FunctionCallOutput -> encoder.encodeSerializableValue(FunctionCallOutput.serializer(), value)
          is ToolSearchCall -> encoder.encodeSerializableValue(ToolSearchCall.serializer(), value)
          is ToolSearchOutput -> encoder.encodeSerializableValue(ToolSearchOutput.serializer(), value)
          is Reasoning -> encoder.encodeSerializableValue(Reasoning.serializer(), value)
          is Compaction -> encoder.encodeSerializableValue(Compaction.serializer(), value)
          is ImageGenerationCall -> encoder.encodeSerializableValue(ImageGenerationCall.serializer(), value)
          is CodeInterpreterCall -> encoder.encodeSerializableValue(CodeInterpreterCall.serializer(), value)
          is LocalShellCall -> encoder.encodeSerializableValue(LocalShellCall.serializer(), value)
          is LocalShellCallOutput -> encoder.encodeSerializableValue(LocalShellCallOutput.serializer(), value)
          is ShellCall -> encoder.encodeSerializableValue(ShellCall.serializer(), value)
          is ShellCallOutput -> encoder.encodeSerializableValue(ShellCallOutput.serializer(), value)
          is ApplyPatchCall -> encoder.encodeSerializableValue(ApplyPatchCall.serializer(), value)
          is ApplyPatchCallOutput -> encoder.encodeSerializableValue(ApplyPatchCallOutput.serializer(), value)
          is McpListTools -> encoder.encodeSerializableValue(McpListTools.serializer(), value)
          is McpApprovalRequest -> encoder.encodeSerializableValue(McpApprovalRequest.serializer(), value)
          is McpApprovalResponse -> encoder.encodeSerializableValue(McpApprovalResponse.serializer(), value)
          is McpCall -> encoder.encodeSerializableValue(McpCall.serializer(), value)
          is CustomToolCallOutput -> encoder.encodeSerializableValue(CustomToolCallOutput.serializer(), value)
          is CustomToolCall -> encoder.encodeSerializableValue(CustomToolCall.serializer(), value)
        }
      }
    }
  }

  /**
   * An internal identifier for an item to reference.
   */
  @Serializable
  public data class ItemReference(
    public val type: Type? = null,
    public val id: String,
  ) : InputItem {
    @Serializable
    public enum class Type(
      public val `value`: String,
    ) {
      @SerialName("item_reference")
      ItemReference("item_reference"),
      ;
    }
  }

  public object Serializer : KSerializer<InputItem> {
    @OptIn(
      InternalSerializationApi::class,
      ExperimentalSerializationApi::class,
    )
    override val descriptor: SerialDescriptor =
        buildSerialDescriptor("io.openai.model.InputItem", PolymorphicKind.SEALED) {
      element("Message", Message.serializer().descriptor)
      element("Item", Item.serializer().descriptor)
      element("ItemReference", ItemReference.serializer().descriptor)
    }

    override fun deserialize(decoder: Decoder): InputItem {
      val value = decoder.decodeSerializableValue(JsonElement.serializer())
      val json = requireNotNull(decoder as? JsonDecoder) { "Complex unions currently only supported for Json" }.json
      val obj = value as? JsonObject
      val tag = (obj?.get("type") as? JsonPrimitive)?.content
      when(tag) {
        "file_search_call", "computer_call", "computer_call_output", "web_search_call", "function_call", "function_call_output", "tool_search_call", "tool_search_output", "reasoning", "compaction", "image_generation_call", "code_interpreter_call", "local_shell_call", "local_shell_call_output", "shell_call", "shell_call_output", "apply_patch_call", "apply_patch_call_output", "mcp_list_tools", "mcp_approval_request", "mcp_approval_response", "mcp_call", "custom_tool_call_output", "custom_tool_call" -> return json.decodeFromJsonElement(Item.serializer(), value)
        "item_reference" -> return json.decodeFromJsonElement(ItemReference.serializer(), value)
        "message" -> {
          return json.attemptDeserialize(
            value,
            Message::class to { decodeFromJsonElement(Message.serializer(), it) },
            Item::class to { decodeFromJsonElement(Item.serializer(), it) },
          )
        }
        else -> throw SerializationException("Unknown tag: " + tag + " for io.openai.model.InputItem")
      }
    }

    override fun serialize(encoder: Encoder, `value`: InputItem) {
      when(value) {
        is Message -> encoder.encodeSerializableValue(Message.serializer(), value)
        is Item -> encoder.encodeSerializableValue(Item.serializer(), value)
        is ItemReference -> encoder.encodeSerializableValue(ItemReference.serializer(), value)
      }
    }
  }
}
