name: "Pull Request"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew build koverXmlReport --full-stacktrace

      - uses: mi-kas/kover-report@v1
        with:
          path: build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          coverage-counter-type: LINE
