package io.github.nomisrev.model

import kotlinx.datetime.LocalDateTime
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class OrganizationFull(
    val login: String,
    val id: Long,
    @SerialName("node_id") val nodeId: String,
    val url: String,
    @SerialName("repos_url") val reposUrl: String,
    @SerialName("events_url") val eventsUrl: String,
    @SerialName("hooks_url") val hooksUrl: String,
    @SerialName("issues_url") val issuesUrl: String,
    @SerialName("members_url") val membersUrl: String,
    @SerialName("public_members_url") val publicMembersUrl: String,
    @SerialName("avatar_url") val avatarUrl: String,
    val description: String?,
    val name: String? = null,
    val company: String? = null,
    val blog: String? = null,
    val location: String? = null,
    val email: String? = null,
    @SerialName("twitter_username") val twitterUsername: String? = null,
    @SerialName("is_verified") val isVerified: Boolean? = null,
    @SerialName("has_organization_projects") val hasOrganizationProjects: Boolean,
    @SerialName("has_repository_projects") val hasRepositoryProjects: Boolean,
    @SerialName("public_repos") val publicRepos: Long,
    @SerialName("public_gists") val publicGists: Long,
    val followers: Long,
    val following: Long,
    @SerialName("html_url") val htmlUrl: String,
    val type: String,
    @SerialName("total_private_repos") val totalPrivateRepos: Long? = null,
    @SerialName("owned_private_repos") val ownedPrivateRepos: Long? = null,
    @SerialName("private_gists") val privateGists: Long? = null,
    @SerialName("disk_usage") val diskUsage: Long? = null,
    val collaborators: Long? = null,
    @SerialName("billing_email") val billingEmail: String? = null,
    val plan: Plan? = null,
    @SerialName("default_repository_permission") val defaultRepositoryPermission: String? = null,
    @SerialName("default_repository_branch") val defaultRepositoryBranch: String? = null,
    @SerialName("members_can_create_repositories") val membersCanCreateRepositories: Boolean? = null,
    @SerialName("two_factor_requirement_enabled") val twoFactorRequirementEnabled: Boolean? = null,
    @SerialName("members_allowed_repository_creation_type") val membersAllowedRepositoryCreationType: String? = null,
    @SerialName("members_can_create_public_repositories") val membersCanCreatePublicRepositories: Boolean? = null,
    @SerialName("members_can_create_private_repositories") val membersCanCreatePrivateRepositories: Boolean? = null,
    @SerialName("members_can_create_internal_repositories") val membersCanCreateInternalRepositories: Boolean? = null,
    @SerialName("members_can_create_pages") val membersCanCreatePages: Boolean? = null,
    @SerialName("members_can_create_public_pages") val membersCanCreatePublicPages: Boolean? = null,
    @SerialName("members_can_create_private_pages") val membersCanCreatePrivatePages: Boolean? = null,
    @SerialName("members_can_delete_repositories") val membersCanDeleteRepositories: Boolean? = null,
    @SerialName("members_can_change_repo_visibility") val membersCanChangeRepoVisibility: Boolean? = null,
    @SerialName("members_can_invite_outside_collaborators") val membersCanInviteOutsideCollaborators: Boolean? = null,
    @SerialName("members_can_delete_issues") val membersCanDeleteIssues: Boolean? = null,
    @SerialName("display_commenter_full_name_setting_enabled") val displayCommenterFullNameSettingEnabled: Boolean? = null,
    @SerialName("readers_can_create_discussions") val readersCanCreateDiscussions: Boolean? = null,
    @SerialName("members_can_create_teams") val membersCanCreateTeams: Boolean? = null,
    @SerialName("members_can_view_dependency_insights") val membersCanViewDependencyInsights: Boolean? = null,
    @SerialName("members_can_fork_private_repositories") val membersCanForkPrivateRepositories: Boolean? = null,
    @SerialName("web_commit_signoff_required") val webCommitSignoffRequired: Boolean? = null,
    @SerialName("advanced_security_enabled_for_new_repositories") val advancedSecurityEnabledForNewRepositories: Boolean? = null,
    @SerialName("dependabot_alerts_enabled_for_new_repositories") val dependabotAlertsEnabledForNewRepositories: Boolean? = null,
    @SerialName("dependabot_security_updates_enabled_for_new_repositories") val dependabotSecurityUpdatesEnabledForNewRepositories: Boolean? = null,
    @SerialName("dependency_graph_enabled_for_new_repositories") val dependencyGraphEnabledForNewRepositories: Boolean? = null,
    @SerialName("secret_scanning_enabled_for_new_repositories") val secretScanningEnabledForNewRepositories: Boolean? = null,
    @SerialName("secret_scanning_push_protection_enabled_for_new_repositories") val secretScanningPushProtectionEnabledForNewRepositories: Boolean? = null,
    @SerialName("secret_scanning_push_protection_custom_link_enabled") val secretScanningPushProtectionCustomLinkEnabled: Boolean? = null,
    @SerialName("secret_scanning_push_protection_custom_link") val secretScanningPushProtectionCustomLink: String? = null,
    @SerialName("created_at") val createdAt: LocalDateTime,
    @SerialName("updated_at") val updatedAt: LocalDateTime,
    @SerialName("archived_at") val archivedAt: LocalDateTime?,
    @SerialName("deploy_keys_enabled_for_repositories") val deployKeysEnabledForRepositories: Boolean? = null,
) {
    @Serializable
    data class Plan(
        val name: String,
        val space: Long,
        @SerialName("private_repos") val privateRepos: Long,
        @SerialName("filled_seats") val filledSeats: Long? = null,
        val seats: Long? = null,
    )
}
